# Configuracoes do PostgreSQL para producao (perfil 'prod')
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Logging
logging.level.org.hibernate.SQL=WARN